### ISSUE TITLE
Live preview for equations

### ISSUE THREAD

**Issue by PierreMarchand20** [tecosaur/LaTeX-Utilities#10]
### Is your feature request related to a problem? Please describe.

I remember that at some point you wanted to do something similar as For TikZ but for equations, is it still in the road map ?

### Describe the solution you'd like

Showing live the equation, like in markdown for example.

**Comment by PierreMarchand20** [comment]
https://github.com/James-Yu/LaTeX-Workshop/issues/1427 here it is ^^

**Comment by PierreMarchand20** [comment]
Since it was not merged in LaTeX workshop, I just thought it was going to be merged here.

**Comment by tecosaur** [comment]
AFAIK that's a work in progress by @tamuratak. If once it's ready the decision is made not to add it to LW, I'll reopen this issue :slightly_smiling_face:

**Comment by analytic-bias** [comment]
> Since it was not merged in LaTeX workshop, I just thought it was going to be merged here.

Any updates on it?

**Comment by analytic-bias** [comment]
> [microsoft/vscode#85682](https://github.com/microsoft/vscode/issues/85682)
> 
> > This item is currently not planned to be finalized.
> 
> It seems like we won't have this API

So they're going to remove the API from the insiders too?

**Comment by leoleoasd** [comment]
I don't think so 🤔 
Since LaTeX-Workshop already supports preview when hover, I don't think supporting a insider-only feature is worthy.
