### ISSUE TITLE
Count word in LaTeX document leads to ENOENT error (possibly my configuration)

### ISSUE THREAD

**Issue by rlh1994** [tecosaur/LaTeX-Utilities#106]
#### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: **Yes**

### Describe the bug

When running the `Count words in LaTeX docuement` no output is returned, the logs indicate the document path is perhaps not being correctly passed to the script (I think?) `Cannot count words: spawn C:\Users\rlhil\Documents\TeXcount_3_1_1\texcount ENOENT,`. The count works fine when I manually provide the path to the script and .tex file using perl in PowerShell. Possibly a repeat of #47 

### To Reproduce

test.tex
```
\documentclass[10pt]{article}
\begin{document}
\title{A Test doc}
\author{Me}
\date{\today}
\maketitle
\thispagestyle{empty}
\begin{abstract}
Test
\end{abstract}
\clearpage
\section{Test} % (fold)
Test
\end{document}
```

settings.json (tried both with/without using xelatex):
```
{
    "latex-workshop.view.pdf.viewer": "tab",
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-xelatex",
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        }
    ],
    "latex-utilities.countWord.path": "C:\\Users\\rlhil\\Documents\\TeXcount_3_1_1\\texcount",
    "kite.showWelcomeNotificationOnStartup": false
}
```

### Expected behaviour

Whatever the count output should be (I believe an info bar box?)

### Logs

<details>
<summary>LaTeX Workshop Output</summary>

```
Cannot count words: spawn C:\Users\rlhil\Documents\TeXcount_3_1_1\texcount ENOENT, 
```

</details>

### Desktop

-   OS: Windows 10 
-   VS Code version: 1.41.1
-   Extension version: 0.3.4

**Comment by tecosaur** [comment]
To me `ENOENT` suggests that the path to the script could be incorrect. As an initial step, would you be able to confirm that `C:\Users\rlhil\Documents\TeXcount_3_1_1\texcount` is indeed the correct path to the executable, and that no file extension is missing? I haven't used Windows in a bit, but I imagine `texcount.exe` or `texcount.bat` to be the likely file.

Thanks, tecosaur

**Comment by rlh1994** [comment]
That's cleared it up, that file path did contain `texcount.pl`, the perl script for it as I had perl installed and downloaded the file from the linked site, but after compiling it into a `.exe` it's correctly picked it up and working!

**Comment by tecosaur** [comment]
Glad to hear you got it working!
