### ISSUE TITLE
Edit Live Snippets File fails on OSS

### ISSUE THREAD

**Issue by gschaffner** [tecosaur/LaTeX-Utilities#109]
### Description

Running the "Edit Live Snippets File" command produces an error "Running the contributed command: 'latex-utilities.editLiveSnippetsFile' failed."

### Logs

The developer tools console logs show something of interest, but the LaTeX Workshop and LaTeX Utilities logs show nothing out of the ordinary.

<details>
<summary>Developer Tools Console</summary>

```
notificationsAlerts.ts:38 Error: Running the contributed command: 'latex-utilities.editLiveSnippetsFile' failed.
	at v._executeContributedCommand (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:539)
	at v.$executeContributedCommand (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:539)
	at p._doInvokeHandler (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:663)
	at p._invokeHandler (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:662)
	at p._receiveRequest (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:661)
	at p._receiveOneMessage (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:660)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:658
	at l.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
	at _.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:820
	at l.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
	at _.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189)
	at t.PersistentProtocol._receiveMessage (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:193)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:190
	at l.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46)
	at p.acceptChunk (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186
	at Socket.t (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:195)
	at Socket.emit (events.js:200)
	at addChunk (_stream_readable.js:294)
	at readableAddChunk (_stream_readable.js:275)
	at Socket.Readable.push (_stream_readable.js:210)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166)
```

</details>

### Desktop

-   OS: Manjaro Linux
-   VS Code version: 1.41.1
-   Extension version: 0.3.4

### Additional context

I suspect that this issue is due to an incorrect `codeFolder` set [here](https://github.com/tecosaur/LaTeX-Utilities/blob/96754ae7a0a17abcf70799ec2d7c9fbc26e11eba/src/components/completionWatcher.ts#L354). I am running Code - OSS, not Visual Studio Code ([info about the difference](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code)), so my user config is at `~/.config/Code - OSS/User/` instead of `~/.config/Code/User/`.

Thanks for the great work!

**Comment by tecosaur** [comment]
Thanks for the issue, I'll fix that up shortly :) BTW, I ran into this issue myself for some other extensions and so symlinked `~/.config/Code` to `~/.config/Code - OSS` and this seemed to generally be a good mode.

**Comment by tecosaur** [comment]
You can expect this to be in the upcoming `v0.4` release (I want the linter functionality for that).

**Comment by gschaffner** [comment]
Awesome, thanks for the quick fix and the tip!

**Comment by maikol-solis** [comment]
I have the same error with plain Visual Studio Code.

**Comment by ChasingZenith** [comment]
It seems that this issue still happen on may machine today (2020, Mar 26th).
I'm using MacOS and connect my Ubuntu remotely using remote SSH.

## Description

First, I found that even if I set  `"latex-utilities.liveReformat.enabled": true` , I couldn't enjoy live snippet.

Running the "Edit Live Snippets File" command produces an error "Running the contributed command: 'latex-utilities.editLiveSnippetsFile' failed."

I find this issue since I got the same same error.


## How I Solved It

On my remote machine, I ran

```shell
cd ~/.config
ln --symbolic -T Code/ "Code - OSS"
```

Basically it just added a soft link for `~/.config/Code/`

## Logs

Inspired by this discussion above, I checked the *Remote Extension Host Log*, and find that the program is still trying to find `~/.config/Code - OSS/` which is a similar (or the same?) case as @gschaffner and @tecosaur referred to.

<details>
<summary>Log (Remote Extension Host)</summary>

> [2020-03-26 17:33:38.373] [exthost] [error] Error: ENOENT: no such file or directory, open '/home/user/.config/Code - OSS/User/latexUtilsLiveSnippets.json'
> 	at Object.openSync (fs.js:447:3)
> 	at Object.writeFileSync (fs.js:1206:35)
> 	at CompletionWatcher.editSnippetsFile (/home/user/.vscode-server/extensions/tecosaur.latex-utilities-0.3.6/out/src/components/completionWatcher.js:224:18)
> 	at /home/user/.vscode-server/extensions/tecosaur.latex-utilities-0.3.6/out/src/main.js:20:138
> 	at _executeContributedCommand (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:568:220)
> 	at _.$executeContributedCommand (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:568:595)
> 	at p._doInvokeHandler (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:707:464)
> 	at p._invokeHandler (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:707:156)
> 	at p._receiveRequest (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:705:817)
> 	at p._receiveOneMessage (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:704:623)
> 	at /home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:702:791
> 	at l.fire (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:48:845)
> 	at v.fire (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:191:325)
> 	at /home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:870:104
> 	at l.fire (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:48:845)
> 	at v.fire (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:191:325)
> 	at t.PersistentProtocol._receiveMessage (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:195:717)
> 	at /home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:194:881
> 	at l.fire (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:48:845)
> 	at p.acceptChunk (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:188:897)
> 	at /home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:188:249
> 	at Socket.t (/home/user/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/vs/server/remoteExtensionHostProcess.js:197:232)
> 	at Socket.emit (events.js:200:13)
> 	at addChunk (_stream_readable.js:294:12)
> 	at readableAddChunk (_stream_readable.js:275:11)
> 	at Socket.Readable.push (_stream_readable.js:210:10)
> 	at TCP.onStreamRead (internal/stream_base_commons.js:166:17) latex-utilities.editLiveSnippetsFile

</details>


## Desktop

- local OS: MacOS High Sierra

- remote OS: Ubuntu 19.10

- VS Code version: 1.43.2 (both local and remote)

- Extension version: 0.3.6


## Additional context

Thanks for the great work! It is really really fancy, cool and productive, even using it remotely.

**Comment by Filip-K** [comment]
I also just bumped into this issue in plain Visual Studio Code. The workaround is to symlink `~/.config/Code - OSS/` to `~/.config/Code/`, as @ChasingZenith suggested.
