### ISSUE TITLE
Activate/Deactivate features

### ISSUE THREAD

**Issue by PierreMarchand20** [tecosaur/LaTeX-Utilities#11]
### Is your feature request related to a problem? Please describe.

I read some of the history of moving some features from LW to LU, and it looks promising. The issue I see with LU though is that it will rapidly end up with a lot of new features that can be quite unrelated to one another (which is already the case I think).

### Describe the solution you'd like

I do not know how (it is more a thought than a feature request...), but we should always be able to pick the features with want to activate. It is already the case for most of the features (expect formattedPaste from what I have seen), but may be it would be a good idea to organise the code as modularly as possible (which you may have already done, again, just a thought), because I guess it is better to organise the code like that from the start.

**Comment by PierreMarchand20** [comment]
For example, the undocumented feature `texdef` really does not work for now and it would be nice if I could deactivate it ^^

**Comment by joulev** [comment]
@PierreMarchand20 `texdef` is working for me. Have you tried "Go to definition" with any command? In most cases (not all cases) it works.

**Comment by PierreMarchand20** [comment]
Actually I did not try, I just received a lot of notifications telling me that each command I used was not defined. So for now I disabled the extension.

**Comment by PierreMarchand20** [comment]
![image](https://user-images.githubusercontent.com/15056323/63583168-c1e29c00-c59a-11e9-9830-f934437920bd.png)

**Comment by PierreMarchand20** [comment]
(but I should open another issue about it)

**Comment by joulev** [comment]
> ![image](https://user-images.githubusercontent.com/15056323/63583168-c1e29c00-c59a-11e9-9830-f934437920bd.png)

Yes, `\mathbf` can not yet be found. This is either an issue of `texdef` command or the command configuration of LaTeX Utilities. I think the latter has a higher chance of happening. But by the time the feature is actually published, this may have been fixed.

**Comment by tecosaur** [comment]
With formatted paste, I don't see the need for a toggle. It's lightweight and if you don't want to use it just don't press `Cmd`+`Shift`+`V` :slightly_smiling_face:.

For `texdef` though, particularly since it seems problematic now, that sounds like a good idea.

**Comment by tecosaur** [comment]
With regards to code organisation, I appreciate you bringing that up. This is currently a small extension and it's always better to keep things tidy from the beginning. I currently feel fairly happy with the way things are. Aside from writing the functionality, adding/removing a (significant) feature minimally consists of
 - About two lines in `main.ts`
 - A `feature.ts` file somewhere

So we should be good :smile:, but thank you for your concern.

**Comment by PierreMarchand20** [comment]
perfect then ! Looking forward to seeing the new features you will want to add then ^^

**Comment by tecosaur** [comment]
@PierreMarchand20 you'll find that a texdef toggle has been added in v0.2.2 (f94dbcddb3ba24df1a06a3a5891169c407ba60c5).
