### ISSUE TITLE
Tikz preview does not work with pgfplot and reading data

### ISSUE THREAD

**Issue by PierreMarchand20** [tecosaur/LaTeX-Utilities#12]
### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: Yes

### Describe the bug

Reading data from external file with pgfplot does not work.

### To Reproduce

Steps to reproduce the behaviour:

`data.csv`
```
1
3
5
5
```

plot.tex
```
\documentclass[tikz]{standalone}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}
\begin{document}
    \begin{standalone}
        \begin{tikzpicture}
            \begin{axis}[grid]
                \addplot table[x expr= \coordindex, y index= 0] {data.csv};
            \end{axis}
        \end{tikzpicture}  
    \end{standalone}
\end{document}
```
### Expected behaviour

We should see the plot

### Screenshots

![image](https://user-images.githubusercontent.com/15056323/63580152-7a591180-c594-11e9-88fd-e8058812c9ca.png)

### Desktop

-   OS: macOS 10.14.6
-   VS Code version: 1.37.1
-   Extension version: 0.2.1

**Comment by PierreMarchand20** [comment]
A wild guess would be that there is an issue with the path.

**Comment by joulev** [comment]
@PierreMarchand20 As of your second comment, this has nothing to do with the path. The source code for the preview simply doesn't include any external files, or even "local" files using `filecontents`.

**Comment by PierreMarchand20** [comment]
But the code of the preview takes the code of my tikzpicture no ? So it should use `\addplot table[x expr= \coordindex, y index= 0] {data.csv};`.

**Comment by joulev** [comment]
If you want to see the source code of the preview:

<details>
<summary>Main</summary>

```latex
%&preamble
\begin{document}
\begin{tikzpicture}
            \begin{axis}[grid]
                \addplot table[x expr= \coordindex, y index= 0] {data.csv};
            \end{axis}
        \end{tikzpicture}
\end{document}
```
</details>

<details>
<summary>Preamble</summary>

```latex
\documentclass{standalone}


\usepackage{tikz}

\usepackage{pgfplots}
\pgfplotsset{compat=newest}

\pdfcompresslevel=0
\pdfobjcompresslevel=0

\begin{document}\end{document}
```
</details>

(the source code is divided into two files)

**Comment by tecosaur** [comment]
@PierreMarchand20 this is fairly easy to diagnose. Your code contains a reference to `data.csv`. The preview works by copying the tizkpicture region into a new file in a tmp dir. It doesn't know to take a copy of / change the reference to `data.csv`, hence when compiling LaTeX looks for `data.csv` in `/tmp/../tikzpreview/...` (ish) and can't find it.

I currently can't think of any simple solutions to this, so I'll close the issue, but if you have any bright ideas / really want this I'l love to see a PR :smiley:.

**Comment by PierreMarchand20** [comment]
Ok, I thought you could use the absolute path of the original file and the one of the preview to modify accordingly the path of the data.

FYI, there is a similar issue with using `\includestandalone` from the package `standalone`: https://bitbucket.org/martin_scharrer/standalone/issues/41/automated-path-for-pgfplots-grafics-with

**Comment by esillekens** [comment]
for what it's worth, a workaround could be:

\documentclass{standalone}


\usepackage{tikz}

\usepackage{pgfplots}
\pgfplotsset{compat=newest}
\pgfplotsset{
    **table/search path={/home/user/path/to/root/dir},**
}

\usepgfplotslibrary{colorbrewer}



\pdfcompresslevel=0
\pdfobjcompresslevel=0

\begin{document}\end{document}

**Comment by tecosaur** [comment]
That looks promising, I'll give that a shot!
