### ISSUE TITLE
0.3.5 breaks "cite from zotero"

### ISSUE THREAD

**Issue by assignUser** [tecosaur/LaTeX-Utilities#120]
I just received the update to 0.3.5 an hour ago and noticed that it breaks citing from zotero. Returning to 0.3.4 fixes the issue.

### To Reproduce

1. start citing from zotero
2. type anything
3. nothing happens

output log:
```
[15:14:14] Searching Zotero for "d"
[15:14:14] Searching Zotero failed: The `body`, `json` and `form` options are mutually exclusive
``` 

-   OS: Windows 10
-   VS Code version: 1.41.1
-   Extension version: 0.3.5

**Comment by tecosaur** [comment]
Ouch, sorry about that I'll take a look.

**Comment by assignUser** [comment]
Removed 0.3.5 completly and installed again to make sure my tempering with some of the js files wasnt the cause. Error presists eventhough i cant find big changes in zotero.js?

**Comment by tecosaur** [comment]
Yea, I'm not sure what's caused it. The changes to `zotero.ts` are minimal, and the
```ts
        const req = got.post(`${zoteroUrl}/better-bibtex/json-rpc`, {
            body: {
                jsonrpc: '2.0',
                method: 'item.search',
                params: [terms]
            },
            json: true
        })
```
bit wasn't touched. However I think the `got` dependancy was upgraded, and this may have broken something. I'm taking a look at that now.

**Comment by tecosaur** [comment]
I have a fix, the error was due to API changes in `got`. Will push shortly,.
