### ISSUE TITLE
Discrepancy in word count

### ISSUE THREAD

**Issue by werunom** [tecosaur/LaTeX-Utilities#134]
#### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: **Yes**

### Describe the bug

At present there are two ways to get the word-count of tex files: 
1. The status-bar 
2. The command in the pallette

However, when I was working on a tex file, I realised that these two commands end up showing different word-counts. The first one was showing `9746` and the second one `8743`. (This discrepancy turned out to be a real road blocker for the submission of the paper I was working on because the journal had a specific word-limit and I was basing the length of the paper only on option (2).

Since I cannot share the actual paper I am working on, I am sharing a minimum working example to highlight the differences. See the screenshot. 

![test-2](https://user-images.githubusercontent.com/24664855/75610314-3abc4500-5b36-11ea-9304-43f3fc3cd021.png)

I observed that option (1) includes the words in the title too. Contrast to that, option (2) shows (as the notification shows) only the count from the main-text: `random-text` and the cite-command `\autocite{author}`.

In this small working example itself there is a difference. However, when we are working on real papers which includes lot of commented texts, preamble, etc., the discrepancy can escalate. Given this, I would request you to look into this. 

### Desktop

-   OS: Linux
-   VS Code version: 1.42.1
-   Extension version: 0.3.6

**Comment by tecosaur** [comment]
That certainly should not be happening. I'll take a look :+1:

**Comment by werunom** [comment]
Sure. And thanks!

I also have a related query: if I want the count operation provided by this extension to include bibliography too, how should I pass the parameter? As in the [FAQ of texcount](https://app.uio.no/ifi/texcount/faq.html) mentions, I need to append `-incbib` to the texcount command. I notice that there is currently the option of `Count word: path`. However, since the instructions were not clear, I thought of asking your what to provide in this settings value.  

Please do let me know.

**Comment by leoleoasd** [comment]
Since the texcount feature of the Workshop doesn't include the status bar feature, I continue to maintain this.
After some digging, I found this is intended, see [here](https://github.com/tecosaur/LaTeX-Utilities/blob/master/src/components/wordCounter.ts#L229-L245).
If you need the same number, change `${words}` in the template to `${wordsBody}`.

Maybe we should change the default behavior to use `${wordsBody}`, or allow users to choose which one to use when using `pickFormat`?
