### ISSUE TITLE
Support tikz fragments

### ISSUE THREAD

**Issue by david-waterworth** [tecosaur/LaTeX-Utilities#15]
is it possible to configure LaTeX Utils such that it treats *.tikz files as LaTeZ files? 

I have a `figures` folder under my document root which contains my tikz preamble and tikz images as fragments. In my main document I use \input to import them into the document i.e.

\input{./figures/preamble.tikz}

\begin{document}
\begin{figure}[ht]
    \input{./figures/controller.tikz}
\end{figure}
\end{document}

I know I can set the Tikzpreview: Preamble Contents to point to the ./preamble.tikz file but because controller.tikz isn't treated as a tex file the preview doesn't work. Changing the file to controller.tex works.

Naming them as *.tex is ok, but the issue is each time I save them LaTeX workshop tried to build them as if they were standalone documents rather than fragments.

**Comment by tecosaur** [comment]
Hello. For the treating `*.tikz` as latex files I feel this would be more appropriate in https://github.com/James-Yu/LaTeX-Workshop/issues, do come back if that gets rejected though!

Not sure why a non-`.tex` file extension doesn't work for the custom preamble though… a quick squiz at the codebase pulls up this section
```ts
if (fs.existsSync(newCommandFile)) {
    commandsString = await fs.readFileSync(newCommandFile, { encoding: 'utf8'})
}
```
So I don't know why `*.tikz` doesn't work.

**Comment by PierreMarchand20** [comment]
Just put `"files.associations": {"*.tikz" : "latex"},` in your settings. It works for me

**Comment by PierreMarchand20** [comment]
Did you set `"files.associations": {"*.tikz" : "latex"},` ?

**Comment by tecosaur** [comment]
That sounds like it would be a solution! Forgot that you could do that, if that solves this I'll just close this issue. @david-waterworth please let me know if that works for you.

**Comment by david-waterworth** [comment]
Sorry I wasn't clear - a non-`.tex` file extension works fine for the custom preamble. The issue was the LaTex-Utils hyperlink wasn't displayed in a non-`.tex` file. But @PierreMarchand20 `"files.associations": {"*.tikz" : "latex"}` suggestion does work thanks! I thought perhaps it might make Latex-Workshop attempt to build the file *.tikz file each time it changed but it doesn't appear to.

**Comment by tecosaur** [comment]
So, is there anything left that you want to be done, or are we good to close this issue? :smiley:

**Comment by david-waterworth** [comment]
No I'm happy to close!
