### ISSUE TITLE
shift + cmd + v doesn't work

### ISSUE THREAD

**Issue by vaagee** [tecosaur/LaTeX-Utilities#153]
With LaTeX Utilities enabled in VS Code 1.44.0 on macOS 10.15.4, `shift` + `cmd` + `v` gives no response. The Formmated Paste works well if I call it from the Command Palette or by `cmd` + `v` if I set `"latex-utilities.formattedPaste.useAsDefault"` as `"true"` in the "setting.json". There are three other commands in my shortcuts list, I don't know if there's a conflict.

 >{ 
 "key": "shift+cmd+v",
  "command": "markdown-preview-enhanced.openPreview",
  "when": "editorLangId == 'markdown'"
  }

 >{
 "key": "shift+cmd+v",
  "command": "markdown.showPreview",
  "when": "editorLangId == 'markdown'"
   }

  >{
  "key": "shift+cmd+v",
  "command": "markdown.extension.togglePreview",
  "when": "!terminalFocus"
   }

>

**Comment by tecosaur** [comment]
It does look like
```json
{
"key": "shift+cmd+v",
"command": "markdown.extension.togglePreview",
"when": "!terminalFocus"
}
```
Would be active in `LaTeX` files, and could quite posibly be interfering. Adding a language condition may help.

**Comment by vaagee** [comment]
> It does look like
> 
> ```json
> {
> "key": "shift+cmd+v",
> "command": "markdown.extension.togglePreview",
> "when": "!terminalFocus"
> }
> ```
> 
> Would be active in `LaTeX` files, and could quite posibly be interfering. Adding a language condition may help.

**Comment by vaagee** [comment]
> It does look like
> 
> ```json
> {
> "key": "shift+cmd+v",
> "command": "markdown.extension.togglePreview",
> "when": "!terminalFocus"
> }
> ```
> 
> Would be active in `LaTeX` files, and could quite posibly be interfering. Adding a language condition may help.

Problem solved! Many thanks!
