### ISSUE TITLE
Image pasting doesn't work on remote development

### ISSUE THREAD

**Issue by garyng** [tecosaur/LaTeX-Utilities#25]
## Bug Report

Seem like the [`pasteImage`](https://github.com/tecosaur/LaTeX-Utilities/blob/master/src/components/paster.ts#L247) function calls [`saveClipboardImageToFileAndGetPath`](https://github.com/tecosaur/LaTeX-Utilities/blob/master/src/components/paster.ts#L460) that uses platform-dependent scripts to get the content of the clipboard instead of using the [vscode clipboard API](https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-clipboard). 

### To Reproduce

Steps to reproduce the behaviour:

1. Use `LaTeX-Utilities` inside a container
2. Copy and paste an image
3. It shows `No image in clipboard`
![image](https://user-images.githubusercontent.com/4453664/64068429-90d52c00-cc6a-11e9-8b61-7a3abd5f8bde.png)

### Expected behaviour

The image should be pasted.

**Comment by garyng** [comment]
Just realized that `vscode.env.clipboard` has only `readText` and `writeText`...

**Comment by tecosaur** [comment]
It would be nice if vscode provided a more fleshed out clipboard api, but unfortunately that isn't the case. I don't see any easy way to get around this, but if you can I'd love to see a PR.
