### ISSUE TITLE
Incorrect folder path separator at image paste

### ISSUE THREAD

**Issue by spbroma** [tecosaur/LaTeX-Utilities#27]
### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: Yes

### Describe the bug
OS: Windows 10

1. When I paste an image from clipboard, I add folder to path "img/image2020.png", but in code it becomes "img\image2020.png" (slash in changed) and LaTeX can'r find image file.

2. It would be great, if in extension settings I could set default subfolder of project to save images. It would be useful also because now extension don't increment filename, if I save them in subfolder

### To Reproduce

Steps to reproduce the behaviour:

1. Copy some image to clipboard
2. Go to LaTeX file
3. Go to LaTeX Utilities: Paste formatted content
4. Add subfolder to name (e.g. "img/image2020.png")
5. Try to build pdf

### Expected behaviour

To get the same path, as I set: "img/image2020.png" 

### Logs

Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

I think, logs are not necessary.

### Screenshots

![image](https://user-images.githubusercontent.com/1898310/64211770-de8ea600-ceaf-11e9-8479-908d1ab4d86f.png)

### Desktop

-   OS: Windows 10
-   VS Code version: 1.37.1
-   Extension version: 8.1.0/0.2.2 (LaTeX Workshop / LaTeX Utilities)

**Comment by tecosaur** [comment]
Ok. Sounds like this can be fixed just by ensuring Unix-style paths. I'll have a look (you may have to wait a week or two though).

**Comment by tecosaur** [comment]
Haven't tested the solution, but I'm hopeful. Let me know if you have any more issues.

**Comment by spbroma** [comment]
Yes, it solved my problem. Thank you!
