### ISSUE TITLE
Support circuitikz

### ISSUE THREAD

**Issue by david-waterworth** [tecosaur/LaTeX-Utilities#30]
`circuitikz` is a tikz derivative package for typesetting electrical circuits (https://www.overleaf.com/learn/latex/CircuiTikz_package). Is there a way of configuring `Latex-Utilities` to display circuitikz images? If not could it be added? I assume you need to recognise the \begin{circuitikz} / \end{circuitikz} environment and load the circuitikz package and hopefully that's enough?

i.e. 
        \usepackage{circuitikz}

        \begin{circuitikz}[american voltages, american currents]
            \draw
            % rotor circuit
            (0,0) to [short] (4,0)
            node[label={$T_z$}] {}
            (4,0) to [R, l=$R_b$] (6,0)
            node[label={$T_b$}] {}
            (6,0) to [R, l=$R_e$] (8,0)
            (0,-3) to [I, l_=$\dot{Q}_{c}$] (0,0) % cooling
            (2,-3) to [I, l_=$\dot{Q}_{o}$] (2,0) % occupancy
            (4,-3) to [C, l_=$C_z$, -*] (4,0) % zone capacitance
            (6,-3) to [C, l_=$C_b$, -*] (6,0) % building capacitance
            (8,0) to [V, v=$T_e$, *-] (8,-3) % external temp
            (8,-3) to [short] (0,-3)
            ;
        \end{circuitikz}

**Comment by tecosaur** [comment]
This sounds reasonable. I'll give it a look :smiley:

**Comment by tecosaur** [comment]
At some point, I swear.
(sorry for the delay, I will get around to it)
