### ISSUE TITLE
Graphicspath not being determined

### ISSUE THREAD

**Issue by spbroma** [tecosaur/LaTeX-Utilities#32]
### Is your feature request related to a problem? Please describe.

It could be useful to define folder to save pictures from clipboard by default, Instead of current folder.

### Describe alternatives you've considered

Now you can specify folder path, but it wouldn't increment name of image.

**Comment by tecosaur** [comment]
For folders, if you specify `\graphicspath{abc}` it will automatically put images in the `abc/` folder.

**Comment by tecosaur** [comment]
@spbroma does that help you?

**Comment by spbroma** [comment]
Maybe, I do something wrong, but no
![image](https://user-images.githubusercontent.com/1898310/64927493-184a9f80-d814-11e9-917f-ca17c0c1175f.png)

**Comment by tecosaur** [comment]
Hmm. It looks like your graphics path isn't being determined. To determine that this extension actually makes use of an API provided by LaTeX-Workshop (specifically I call `this.extension.workshop.getGraphicsPath()`), this _may_ be a problem that end.

Looking at the regex used in LaTeX-Workshop, it seems that your `\graphicspath{img}` doesn't match it. See https://regex101.com/r/CJtPPA/1. If you confirm that this LaTeX code is valid (i.e. works) then I'll make a PR over there to fix that.

**Comment by spbroma** [comment]
It seems to work in the following case:

1. I set it as `\graphicspath{{img}}` (in double brackets)
2. Restart VS Code
3. Paste image and it appears in `img/` folder (if is exists)
4. But! Pasted  string will be like `\includegraphics{image1.png}` and LaTeX will fall during compiling and it will work only if add folder to path as `\includegraphics{pic/image1.png}`

![image](https://user-images.githubusercontent.com/1898310/64995231-58c51e80-d8e3-11e9-9f16-2a47600420c6.png)

**Comment by tecosaur** [comment]
That's ... odd. Looking at your screenshot of the file that looks like it _should_ compile fine. I'll do a quick check later today.

**Comment by tecosaur** [comment]
@spbroma what if you put a slash at the end of `img`? I.e. `\graphicspath{{img/}}`

**Comment by spbroma** [comment]
It works! Thank you!

**Comment by tecosaur** [comment]
Sorry I gave you a slightly dodgy induction to start with, I'm glad you've now got a system that works :smile:
