### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by AtheistApe** [tecosaur/LaTeX-Utilities#35]
Greetings,
I've been searching, unsuccessfully, for documentation on how to customize the image paste feature. It is unclear which file needs to be modified and what needs to be put there to get the functionality shown in the "demo" of this feature.

There doesn't seem to be any clear documentation of this package.

**Comment by tecosaur** [comment]
Hi Ape,

I like to think that the vscode settings are fairly good at explaining themselves,

![image](https://user-images.githubusercontent.com/20903656/64943996-c7808880-d89f-11e9-9a34-bf6b2691c44a.png)

We happen to have a wiki which (as of just now) happens to contain exactly what you're looking for! See https://github.com/tecosaur/LaTeX-Utilities/wiki/Formatted-Paste#images.

I've also added a link to the wiki to the readme — aa60934fe2a93ca256dbb040f743da1f7bc2601f.

I feel like that should do the trick :)
