### ISSUE TITLE
No reponse with "cmd+shift+v" to paste anything

### ISSUE THREAD

**Issue by hiuxia** [tecosaur/LaTeX-Utilities#355]
### System information 
My system version is `Macos 12.0` and vscode version is up-to-date. 
### issue-description
Can not get any response when trying to paste sth with the default shortcut **cmd+shift+v**
### Disable all other extensions and retry 
Yes, but still cannot get any response.

Sorry to bother.

**Comment by leoleoasd** [comment]
Hi @hiuxia could you try open the Command Palette and invoke formatted paste command?

**Comment by hiuxia** [comment]
使用`command pallette` 仍然没有反应，但是使用快捷键会黏贴`image.png`的字样。

There is no reponse using  the `command pallete`, but a string `image.png` will be generated  using the shortcut.

**Comment by hiuxia** [comment]
There is no reponse using the command pallete, but a string image.png will be generated using the shortcut.

**Comment by leoleoasd** [comment]
@hiuxia 试一下最新的 0.4.5 版本？

刚发布，可能需要等1，2分钟才能上线

**Comment by hiuxia** [comment]
谢谢大神！已经可以了。能冒昧的问一下是因为vscode 版本的问题吗？我查阅资料发现好像是v8有问题？

Thank you! it is ready. I wondered if the origin for this bug? I checked the information and found that there seems to be a problem with v8?

**Comment by leoleoasd** [comment]
因为昨天的那个版本有bug😭
