### ISSUE TITLE
Formatting failed. Please refer to LaTeX Workshop Output for details.

### ISSUE THREAD

**Issue by carveybunt** [tecosaur/LaTeX-Utilities#357]
### Describe the bug
The Live Snippets can't work and I got the error: `Formatting failed. Please refer to LaTeX Workshop Output for details`. When I build the Latex project after I set `"latex-utilities.liveReformat.enabled": true`. But I set `"latex-utilities.liveReformat.enabled": false`, build was success. 

### To Reproduce

Steps to reproduce the behaviour:

1. Setting `"latex-utilities.liveReformat.enabled": true`.
2. Build the Latex project.
3. See an error

### Expected behaviour

Set `"latex-utilities.liveReformat.enabled": true` and make Live Snippets work and build success.

### Screenshots
plugins settings:
![截屏2022-08-18 11 51 15](https://user-images.githubusercontent.com/37894474/185289750-6edd3a63-8cf4-4283-824f-b946889d76b8.png)
error for build:
![截屏2022-08-18 11 52 00](https://user-images.githubusercontent.com/37894474/185289775-323515d0-ed19-47ce-9c64-6b2d98973242.png)
latex-utilities not work:
![截屏2022-08-18 11 52 38](https://user-images.githubusercontent.com/37894474/185289801-8f118d42-a1f4-4119-af7c-6dd8e842246c.png)

### Desktop

-   OS: MacOS 12.5
-   VS Code version: 1.70.1
-   LaTeX Workshop: 8.28.0
-   LaTeX Utilities: v0.4.6
-   MacTeX: 2022

### Additional context
example code:
```tex
\documentclass[dvisvgm]{standalone} 
\usepackage{tikz } 

\begin{document}
\begin{tikzpicture}[> = latex, scale = .5]
    \draw [fill=blue](-4,0)node[above]{$C$}--(0,3)node[right]{$B$}--(4,0)node[above]{$A$}--(0,-3)node[right]{$D$}--(-4,0); 
    \draw[->] (-6,0)--(6,0)node[right]{$x$};
    \draw[->] (0,-6)--(0,6)node[right]{$y$};
    \node at (-.4,-.4){$O$};
    \foreach \x in {1,2,...,5}
    {
        \draw (0,\x)node[left]{$\x$}--(.1,\x); 
        \draw (\x,0)node[below]{$\x$}--(\x,.1);
    }
    

\end{tikzpicture}

\end{document}
```
My vscode settings:
```json
  "latex-workshop.latex.tools": [
    {
      "name": "xelatex",
      "command": "xelatex", 
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-no-pdf",
        "%DOCFILE%"
      ]
    },
    {
      "name": "dvisvgm",
      "command": "dvisvgm", 
      "args": [
        // "--synctex=1",
        "--zoom=1",
        "--exact",
        // "--font-format=woff",
        "%DOCFILE%.xdv"
      ]
    }
  ],
  "latex-workshop.latex.recipes": [
    {
      "name": "xdv->svg",
      "tools": ["xelatex", "dvisvgm"]
    }
  ]
```

**Comment by leoleoasd** [comment]
Hi can you attach the screenshot for the error and the log panel?

**Comment by carveybunt** [comment]
> 

Sorry, I forgot then, I updated.

**Comment by leoleoasd** [comment]
Your error isn't about live snippet. You should submit your error to https://github.com/James-Yu/LaTeX-Workshop/.
