### ISSUE TITLE
Manual set graphics path via config

### ISSUE THREAD

**Issue by lublak** [tecosaur/LaTeX-Utilities#360]
### Is your feature request related to a problem? Please describe.

Currently my graphicspath is not correctly detected. All images should go to rootfolder/abbildungen.
```
\graphicspath{{./}{./abbildungen/}}
or
\graphicspath{{./abbildungen/}{./}}
```
my preamble is in a different file. (../.../.../main.tex)

### Describe the solution you'd like

A simple config option to manually set the path without autodetection.

### Describe alternatives you've considered

Improvement of the autodetection.

**Comment by leoleoasd** [comment]
Fixed in 67298ffc636073e2e2e1d8d36767f860695e6f7f
