### ISSUE TITLE
Having a characters count option in addition of the word couting

### ISSUE THREAD

**Issue by dbourrion** [tecosaur/LaTeX-Utilities#367]
Hi folks

Here's the "little" problem I'm dealing with : I'm writing novels with LaTeX and VSC.
Words couting is great but publishers often like (or prefer) to have also the precise number of characters that is in a novel.

It would be great to have, in the status bar, in addition of the number of words, the number of characters.

What about that idea ?

**Comment by dbourrion** [comment]
Argh, there another issue about that below. I'm ashamed. Closing. Sorry.

**Comment by leoleoasd** [comment]
I'll take a look tomorrow

**Comment by dbourrion** [comment]
That command line in a linux terminal looks working `texcount -char -sum -1 the_file.tex` but I have no idea how to put this in a VSC extension :(
