### ISSUE TITLE
Unending TeXCount error messages if latex is not installed locally

### ISSUE THREAD

**Issue by rzippo** [tecosaur/LaTeX-Utilities#371]
I am using remote editing, my local environment does not have latex installed.
But the count words feature insists on calling the texcount command locally and I can't seem to find an option to disable it.

**Comment by leoleoasd** [comment]
I'm using remote WSL and the extension can correctly call texcount within WSL. Which type of remote are you using?

**Comment by rzippo** [comment]
SSH. Though, for the build step I use a docker image via LaTeX-Workshop

**Comment by leoleoasd** [comment]
Ok, so the problem should be calling texcount in your remote environment but not inside docker.
try adding this to your settings.json and see if it works:
```
"latex-utilities.countWord.docker.enabled": true,
```

**Comment by rzippo** [comment]
Yes, this works. But it seems it is not documented.

**Comment by leoleoasd** [comment]
Documentation added in v0.4.9.
