### ISSUE TITLE
Changelog has not been updated since v0.4.6

### ISSUE THREAD

**Issue by gschaffner** [tecosaur/LaTeX-Utilities#373]
hi! it looks like `CHANGELOG.md` has not been updated since v0.4.6.

git tags for v0.4.7 and v0.4.8 are also missing.

**Comment by leoleoasd** [comment]
Fixed, and add git tag for v0.4.8.
It seems that I skipped v0.4.7

**Comment by leoleoasd** [comment]
That should be the merge commit for #363

**Comment by leoleoasd** [comment]
Added changelog entry for v0.4.7.
I remembered that my gpg smart card was broken for a long time, I think that's why I didn't commit this version
