### ISSUE TITLE
TeXCount failed

### ISSUE THREAD

**Issue by DarvidTorres** [tecosaur/LaTeX-Utilities#374]
#### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: **Yes, I still see this issue**

### Describe the bug

I keep on receving the message "TeXCount failed. Please refer to LaTeX Utilities Output for details" every time I open a .tex file, everything works as it should, except that I just don't seem to know what is causing the message. 

I got the texcount.pl script set to PATH, but I don't know what to do to the Count Word: Args setting.

### To Reproduce

Steps to reproduce the behaviour:

You can work with .tex files with no problem, render de PDF and everything is ok, the extensions settings are set as default but I keep on receiving the "TeXCount failed. Please refer to LaTeX Utilities Output for details" message. I tryied then to download the texcount.pl script and set the PATH in the LaTeX Utilities extension, and keep seeing the error message.

### Expected behaviour

There shouldn't be a "TeXCount failed. Please refer to LaTeX Utilities Output for details" error message every time you open a .tex file.

### Logs

"TeXCount failed. Please refer to LaTeX Utilities Output for details"

### Desktop

-   OS: Windows 10
-   VS Code version: 1.74.2
-   Extension version: 0.4.6

### Additional context

I don't know if this is an issue or there's another place to ask questions. Thanks

**Comment by leoleoasd** [comment]
Please paste the logs here
![image](https://user-images.githubusercontent.com/37735580/209460181-215a9e9c-18d3-49ec-9b65-acbbce169ffb.png)

**Comment by DarvidTorres** [comment]
[17:03:34] Initializing LaTeX Utilities.
[17:03:34] Live Snippets Loaded
[17:03:34] Completion Watcher Initialised
[17:03:34] TexCount args: -merge,-brief
[17:03:34] Cannot count words: spawn UNKNOWN, undefined
[17:03:34] LaTeX Utilities Started
[17:03:34] LaTeX Utilities version: 0.4.9
[17:04:01] onDidChangeActiveTextEditor_tex_wordcounter
[17:04:35] onDidChangeActiveTextEditor_tex_wordcounter
[17:04:35] TexCount args: -merge,-brief
[17:04:35] Cannot count words: spawn UNKNOWN, undefined
[17:04:45] onDidChangeActiveTextEditor_tex_wordcounter
[17:04:46] onDidChangeActiveTextEditor_tex_wordcounter
[17:04:46] TexCount args: -merge,-brief
[17:04:46] Cannot count words: spawn UNKNOWN, undefined
[17:04:55] onDidChangeActiveTextEditor_tex_wordcounter
[17:05:02] onDidSaveTextDocument_tex_wordcounter
[17:05:05] onDidChangeActiveTextEditor_tex_wordcounter
[17:05:05] TexCount args: -merge,-brief
[17:05:05] Cannot count words: spawn UNKNOWN, undefined
[17:05:09] onDidChangeActiveTextEditor_tex_wordcounter

**Comment by leoleoasd** [comment]
1. please check your `latex-utilities.countWord.path` config, make sure it's your `texcount.pl`.
2. please run `texcount.pl your_tex_file.tex` manually from command line and make sure it works.
3. If the above steps don't work, try manually install this version and re-produce the bug, then paste the logs
  [latex-utilities-0.4.9.zip](https://github.com/tecosaur/LaTeX-Utilities/files/10303587/latex-utilities-0.4.9.zip)

**Comment by DarvidTorres** [comment]
Okay, 

1. There it is the file that I donwloaded from this page: https://app.uio.no/ifi/texcount/download.html ![image](https://user-images.githubusercontent.com/20685823/209562545-d544d7c2-8551-4e46-9d07-639d8cbec85e.png)

Then I set the `latex-utilities.countWord.path` to the file but the error message still appears.

2. I run the `texcount.pl my_tex_file.tex` and it doesn't work, what should I do in this case?

![image](https://user-images.githubusercontent.com/20685823/209563166-712b128f-ea9c-42c3-a699-74dd2ceeaedc.png)

**Comment by leoleoasd** [comment]
1. try use full path `C:\TexCount\texcount.pl` in terminal
2. What tex distribution are you using? AFAIK most distributions come with pre-included texcount

**Comment by DarvidTorres** [comment]
Using the full path it works, there's a window that opens but it's really fast I can't see what it says, but there's no problem with my terminal

![image](https://user-images.githubusercontent.com/20685823/209563478-7a5be97c-fa5e-4ab7-9df9-b413acbb5ba9.png)

I have this LaTex distribution

![image](https://user-images.githubusercontent.com/20685823/209563557-c5fe923e-d656-4d9e-b3df-5b5de3a2b31b.png)

**Comment by leoleoasd** [comment]
https://tex.stackexchange.com/questions/239199/latex-distributions-what-are-their-main-differences
which one in this list are you using?

**Comment by DarvidTorres** [comment]
I have MiKTeX distribution

**Comment by leoleoasd** [comment]
Can you try a tex file whose name doesn't have space in it? Also try looking for texcount in somewhere like `C:\Program Files\MiKTeX\miktex\bin`

**Comment by DarvidTorres** [comment]
I found the `texcount.pl` file within the folder where my MiKTeX distribution is found, then I changed the path in the extension settings to it. I also changed the name of my file so it doesn't have spaces. The rendering, the syntax highlight, everything goes well, except that I still receive the error message. I disabled the extension and the message goes away, then restart VScode and enable the extension, and the message is there again :(

![image](https://user-images.githubusercontent.com/20685823/209565477-5e68add2-666f-4425-a92e-9512e79a895c.png)

![image](https://user-images.githubusercontent.com/20685823/209565508-95894c70-a8c2-4eaa-852f-28eb5268341d.png)

![image](https://user-images.githubusercontent.com/20685823/209565619-98abe31a-592a-481c-9e11-703ed8f98885.png)

**Comment by leoleoasd** [comment]
can you try the vsix I uploaded earlier? that should provide more logs

**Comment by leoleoasd** [comment]
https://github.com/facebook/create-react-app/issues/12465
can you try disabling your anti-virus software?

**Comment by DarvidTorres** [comment]
The only anti-virus I have is the Microsoft Defender Antivirus, and by setting it off, diesabling the extension, then relaunching VScode and enabling it again, the message is still there :( I guess I'm just going to disable the error notifications from VScode so it doesn't bothers me. Thank you

![image](https://user-images.githubusercontent.com/20685823/209566544-6126e206-0306-42bf-ac9f-7761986fb9c0.png)

**Comment by leoleoasd** [comment]
You can set `latex-utilities.message.error.show` to false to disable error logs from latex-utilies. Sorry that I can't provide more help, this weird error seems only happening on your machine

**Comment by UlisesFco** [comment]
I also had this problem. I fixed it by defining `latex-utilities.countWord.path` as the texcount.exe file path from the MikTeX installation folder (`C:\Users\ulise\AppData\Local\Programs\MiKTeX\miktex\bin\x64\texcount.exe` in my case) instead of the one from the texcount.pl file.

**Comment by pnulty** [comment]
Also have this problem on on Mint Linux

**Comment by MalcolmMielle** [comment]
I have this problem on fedora

**Comment by leoleoasd** [comment]
@onulty @MalcolmMielle  Can you paste the log inside the `output` panel of vscode? make sure to select "LaTeX-Utilities" tab
and please try running texcount in your terminal

**Comment by MalcolmMielle** [comment]
My bad I realized that I was missing a bunch of dependencies :(. My bad, sorry for the noise!

**Comment by tomasrei** [comment]
> I also had this problem. I fixed it by defining `latex-utilities.countWord.path` as the texcount.exe file path from the MikTeX installation folder (`C:\Users\ulise\AppData\Local\Programs\MiKTeX\miktex\bin\x64\texcount.exe` in my case) instead of the one from the texcount.pl file.

Thanks for this! I have TeX Live and this made it work (if I use the command palette, I can't recall how it worked before the bug as it was so long ago!)

**Comment by DavidL-Engineering** [comment]
> I also had this problem. I fixed it by defining `latex-utilities.countWord.path` as the texcount.exe file path from the MikTeX installation folder (`C:\Users\ulise\AppData\Local\Programs\MiKTeX\miktex\bin\x64\texcount.exe` in my case) instead of the one from the texcount.pl file.

Seconding that this worked.

**Comment by stutopp** [comment]
I am using `texlive` 2024 on Windows 10 and am encountering the same error in Visual Studio Code. The relevant logs are:

> `[01:09:15] TexCount args: -merge,-brief`
> `[01:09:15] Cannot count words: spawn C:\Program Files\texlive\2024\bin\windows\texcount.exe ENOENT, undefined`

I've tried defining `latex-utilities.countWord.path` as both `texcount.exe` and `texcount.pl` in my texlive install (i.e., `C:\Program Files\texlive\2024\bin\windows\texcount.exe` and  `C:\Program Files\texlive\2024\texmf-dist\scripts\texcount\texcount.pl`); neither have worked. Any additional troubleshooting I can try? TY!

**Comment by fhdupont** [comment]
> I am using `texlive` 2024 on Windows 10 and am encountering the same error in Visual Studio Code. The relevant logs are:
> 
> > `[01:09:15] TexCount args: -merge,-brief`
> > `[01:09:15] Cannot count words: spawn C:\Program Files\texlive\2024\bin\windows\texcount.exe ENOENT, undefined`
> 
> I've tried defining `latex-utilities.countWord.path` as both `texcount.exe` and `texcount.pl` in my texlive install (i.e., `C:\Program Files\texlive\2024\bin\windows\texcount.exe` and `C:\Program Files\texlive\2024\texmf-dist\scripts\texcount\texcount.pl`); neither have worked. Any additional troubleshooting I can try? TY!

I was facing the same issue after installing the current MikTex version on a fresh Windows setup. I ran texcount.exe on terminal and verified that my system didn't have perl installed. So I installed Strawberry perl (https://www.perl.org/get.html#win32), closed/reopened VSCode and everything is working as expected now.

**Comment by stutopp** [comment]
> I was facing the same issue after installing the current MikTex version on a fresh Windows setup. I ran texcount.exe on terminal and verified that my system didn't have perl installed. So I installed Strawberry perl (https://www.perl.org/get.html#win32), closed/reopened VSCode and everything is working as expected now.

I re-installed both TeX Live and Perl and confirmed both were in `PATH` and successfully ran `texcount.exe` in PowerShell. I am still getting the "Cannot count words..." error for both the exe and the script.

**Comment by soldierlambs** [comment]
Hello, i am also experiencing the same issue as the original poster, identical apart from the fact that i am using vscode-server in a Linux container (Tex-Live distribution). Has anyone got any updates on this issue?
