### ISSUE TITLE
Support Zotero via Web API key

### ISSUE THREAD

**Issue by jooyoungseo** [tecosaur/LaTeX-Utilities#377]
I was wondering if there would be any way to access my Zotero library using Zotero web API. I have created my own keys in my Zotero web account, but it does not seem like your extension provides any related settings where users can connect to Zotero via the web API key.

**Comment by leoleoasd** [comment]
This is not currently possible. We are using the json-rpc provided by better bibtex plugin. It isn't available in the Web API.
