### ISSUE TITLE
How to deal with TeXCount failed. Please refer to LaTeX Utilities Output for details.

### ISSUE THREAD

**Issue by HangChi** [tecosaur/LaTeX-Utilities#378]
### Is your feature request related to a problem? Please describe.

A clear and concise description of what the problem is. Ex. I'm always frustrated when...

**Comment by leoleoasd** [comment]
1. 请正确选择issue模板。开启issue的时候应该选择 bug report，并按照其中的提示提交日志。
2. 描述你的问题的时候请不要简单的说『how to deal with something』。请描述：你的环境配置是什么（在我们这个repo的场景下，是你的插件版本、vscode版本、latex编译器版本和安装方式』，你做了什么，预期结果是什么，实际结果是什么。在网络上我们交流一次的时间成本可能是好几天，所以尽可能一次性的提供完整信息，减少互相等待的次数和时间。
3. texcount问题请按照 [这里](https://github.com/tecosaur/LaTeX-Utilities/issues/374#issuecomment-1364638627) 提交日志
