### ISSUE TITLE
Question: How do I save images to a subfolder of the edited documents folder?

### ISSUE THREAD

**Issue by AtheistApe** [tecosaur/LaTeX-Utilities#38]
Greetings,

Is it possible to save images to a subfolder of the documents folder? For example, if the document being edited is in the folder 

/home/gary/documents/latex_files/

I would like images stored in

/home/gary/documents/latex_files/img/

Here's what I currently have in settings.json:

{
    "latex-workshop.view.pdf.viewer": "tab",
    "workbench.colorTheme": "Monokai",
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "window.titleBarStyle": "custom",
    "python.jediEnabled": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "julia.enableTelemetry": true,
    "window.zoomLevel": 1,
    "latex-workshop.intellisense.package.enabled": true,
    "editor.wordWrap": "on",
    "latex-utilities.formattedPaste.image.template": [
        "\\begin{figure}[!htb]",
        "\t\\centering",
        "\t\\includegraphics[$1]{${imageFilePath}}",
        "\t\\caption{${imageFileNameWithoutExt/[-]/ /}}",
        "\t\\label{fig:${imageFileNameWithoutExt}}",
        "\\end{figure}",
        ""
    ],
    "kite.showWelcomeNotificationOnStartup": false
}

Thanks for any help you can provide me.

**Comment by tecosaur** [comment]
You'll probably be interested in [wiki/Formatted-Paste#images](https://github.com/tecosaur/LaTeX-Utilities/wiki/Formatted-Paste#images), more specifically the sentence:

> To determine where the image is saved to, we look for the first location listed in `\graphicspath{{folder1}}`. If we get a result, we save the image to that folder, otherwise we put it in the local folder.

**Comment by AtheistApe** [comment]
Where do I include this "\graphicspath{{folder1}}" line? Does it go in the settings.json file or in some other file. It's not clear in the wiki.

**Comment by tecosaur** [comment]
Oh, that's just in the LaTeX preamble.

**Comment by AtheistApe** [comment]
Okay, I tried each of the following lines in the preamble

\graphicspath{{"./img/"}}
\graphicspath{{./img/}}
\graphicspath{{img/}}

None of them placed images in the  img/  subdirectory of the document. In every case the images were placed in the document's directory. Any idea what I might be doing wrong?

Also, thanks a lot for promptly responding to my questions. I really do appreciate it! :-)

**Comment by tecosaur** [comment]
I would have thought that that last one would have worked. See #32

**Comment by AtheistApe** [comment]
Okay, once I restarted VSCode the last line worked. Thanks again for your help.

**Comment by tecosaur** [comment]
Thank you for your appreciation :stuck_out_tongue: No seriously, this is a small-scale project born from personal interest. It's taken quite a few hours to get to this point, and it's not as if I'm getting paid for it — so, actually hearing people be friendly and appreciative means a great deal.

Thanks.
