### ISSUE TITLE
Could not find definition for \includegraphics

### ISSUE THREAD

**Issue by codingToPerfection** [tecosaur/LaTeX-Utilities#381]
# Could not find definition for \includegraphics

I have already trying `texdef includegraphics` on cmd. it returns undefined. i dont understand why texdef is so incompetent.

![image](https://user-images.githubusercontent.com/126874848/229340170-e296a921-be3e-420c-81ae-e1e6216ca70f.png)

# Could not find definition for \Cref and other common command.
this `could not find definition` window shows frequently. it seems it cant find definitions of other common commands.

**Comment by leoleoasd** [comment]
Do you have `texdef` installed?
If you dont have it, you can disable this feature in settings.

**Comment by codingToPerfection** [comment]
# i installed `texdef` by installing `texlive` latest. I tried the texdef command on cmd. Here's the screenshot. 
I can only assume that texdef is just incompetent.

![image](https://user-images.githubusercontent.com/126874848/229349756-5ebaa414-9452-458c-9cda-d9dbdbba92e8.png)

**Comment by leoleoasd** [comment]
Can you try:
```
latexdef -p graphicx -c article includegraphics
```

**Comment by leoleoasd** [comment]
Also, can you paste the logs in the "output" panel:
![image](https://user-images.githubusercontent.com/37735580/229351501-f5c37c65-d981-411b-972a-a1ebd3f3ab4f.png)
