### ISSUE TITLE
live snippet does not work

### ISSUE THREAD

**Issue by JackYansongLi** [tecosaur/LaTeX-Utilities#390]
#### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: Yes

### Describe the bug

I have made latex-utilities.liveReformat.enabled to true, but the live snippet does not work.

### To Reproduce

Steps to reproduce the behaviour:

1. Install latex-workshop and latex-utility
2. enable latex-utilities.liveReformat.enabled
3. type a1 or => 

### Expected behaviour

a1 should be replaced by a_1 and => by \implies, but it does not happen.

### Logs

Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output</summary>

```
logs here
```

</details>

<details>
<summary>LaTeX Utilities Output</summary>

```
logs here
```

</details>

<details>
<summary>Developer Tools Console</summary>

```
logs here
```

</details>

### Desktop

-   OS: Windows 10 / MacOS / Linux
-   VS Code version: X.Y.Z
-   Extension version: X.Y.Z

**Comment by leoleoasd** [comment]
Please provide more details on how it "does not work".
What did you do? What is the expected behavior? What actually happened?

**Comment by JackYansongLi** [comment]
> Please provide more details on how it "does not work". What did you do? What is the expected behavior? What actually happened?

I just typed a1 and =>, they are not changing to a_1 and \implies

**Comment by leoleoasd** [comment]
Can you take a screenshot?

**Comment by leoleoasd** [comment]
Note that live snippet for math formulas dont work in inline math equations (`$$`). It only works in `\[\]` and `\begin{formula}...`

**Comment by JackYansongLi** [comment]
> Note that live snippet for math formulas dont work in inline math equations (`$$`). It only works in `\[\]` and `\begin{formula}...`

oh! you are right! I didn't see this on the document.

**Comment by leoleoasd** [comment]
You can use `\(\)` for inline equation

**Comment by JackYansongLi** [comment]
> You can use `\(\)` for inline equation

live snippet still does not work for \(\), I am using $...$ for inline formula and \begin{equation} for displayed formula. The live snippet works pretty well for displayed formula

**Comment by leoleoasd** [comment]
replace `$...$` with `\(...\)`

**Comment by JackYansongLi** [comment]
> replace `$...$` with `\(...\)`

does not work, the live snippet is not activated inside \\( ... \\)

**Comment by leoleoasd** [comment]
Can you take a screenshot

**Comment by JackYansongLi** [comment]
> Can you take a screenshot

just type \\(a1 b1 c1\\)

**Comment by JackYansongLi** [comment]
> Can you take a screenshot

I restarted the computer and everything works fine now....
