### ISSUE TITLE
Zotero API Support

### ISSUE THREAD

**Issue by janosh** [tecosaur/LaTeX-Utilities#4]
### Is your feature request related to a problem? Please describe.

Importing references in a Zotero library into a .bib file and keeping that up to date is quite the hassle.

### Describe the solution you'd like

[Zotero offers an API](https://www.zotero.org/support/dev/web_api/v3/basics) which would allow circumventing the manual .bib file creation entirely and could make references citable as soon as they are added to the Zotero library.

### Related issues

- [#1547 in LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop/issues/1547)
- [#3 in vscode-zotero-latex](https://github.com/bnavetta/vscode-zotero-latex/issues/3)

**Comment by tecosaur** [comment]
Waiting for response to https://github.com/bnavetta/vscode-zotero-latex/issues/3

**Comment by coxackie** [comment]
Giving a thumbs up to this - it would be great!

**Comment by tecosaur** [comment]
Done in #29

**Comment by janosh** [comment]
Nice! When's 0.3.0 going to be released? Eager to try it out.

**Comment by tecosaur** [comment]
As soon as `vsce` stops hanging when I try to publish…

**Comment by tecosaur** [comment]
@janosh done!

**Comment by janosh** [comment]
Nice! Really neat UI!

![results](https://user-images.githubusercontent.com/30958850/64428621-1b26f100-d0ac-11e9-99dd-d878bcd68cf9.png)

 For others stumbling across this issue, you need to set
```json
"latex-utilities.zotero.citeMethod": "vscode",
```
to get the native VS Code citation picker.

There's a slight problem I'm encountering, though. It takes several seconds for results to appear from when I start searching for a citation. When I use the Zotero picker, it's almost instant.

**Comment by bnavetta** [comment]
Could you check how many search results you're getting in the LaTeX Utilities output panel? It takes a few seconds for me as well when there are lots of results. I think most of the time is spent waiting for the Zotero search API to return, but there might be a better way of searching.

**Comment by janosh** [comment]
[20:33:22] Got 43 search results from Zotero for "bay"

**Comment by bnavetta** [comment]
I added some profiling around the search code, and it looks like the API request alone took about 2.5 seconds with 55 results. Looking at the Better BibTeX plugin, it uses Zotero's built-in search plus a [search of citation keys](https://github.com/retorquere/zotero-better-bibtex/blob/3aaa6a4495544942a1349f485a7a0f0804c49e2c/content/json-rpc.ts#L47-L52). I think any performance improvements would come from changes to the plugin, but I don't know how easy it would be to speed up.

**Comment by janosh** [comment]
Would it be possible to use the same search algorithm as Zotero's built-in citation picker? I wonder what they do differently that makes them much faster.

**Comment by yoyoyoohh** [comment]
could somebody tell me how to open the citation picker? Keyboard shortcut or something else?

**Comment by janosh** [comment]
@yoyoyoohh A little late perhaps but the command your looking for is called "LaTeX Utilities: Cite from Zotero".

Since you're likely going to use that quite often, you'll want to set a keyboard shortcut for it (<kbd>cmd</kbd>+<kbd>k</kbd> followed by <kbd>cmd</kbd>+<kbd>s</kbd>). I used <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>c</kbd> and set it to only trigger when `editorFocus && editorLangId == 'latex'`.

![zotero-cite-shortcut](https://user-images.githubusercontent.com/30958850/88454186-07c07800-ce6e-11ea-89dd-70f7b9564243.png)

[As mentioned in the readme under requirements](https://github.com/tecosaur/LaTeX-Utilities#requirements), you'll also need [Zotero's Better BibTex](https://retorque.re/zotero-better-bibtex) extension to be installed and set `"latex-utilities.zotero.citeMethod"` from `"zotero"` to `"vscode"` to get the VS Code UI picker rather than the red BBT one.

**VS Code**

![vscode-picker](https://user-images.githubusercontent.com/30958850/88454300-e449fd00-ce6e-11ea-9840-7f8b2d5b0f8b.png)

**BBT**

![bbt-picker](https://user-images.githubusercontent.com/30958850/88454301-e4e29380-ce6e-11ea-90af-3dd36b4d4fb9.png)

**Comment by rubisco57** [comment]
I am wondering if the automatic updating of the .bib file (see @janosh's initial comment) was addressed, and if so, how the API call to add a cited source to a .bib file may be triggered.

**Comment by briochemc** [comment]
> I am wondering if the automatic updating of the .bib file (see @janosh's initial comment) was addressed, and if so, how the API call to add a cited source to a .bib file may be triggered.

I'd like to know this as well!
