### ISSUE TITLE
No image in clipboard

### ISSUE THREAD

**Issue by hktkzyx** [tecosaur/LaTeX-Utilities#40]
### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: Yes

### Describe the bug

When I use formated past to paste an image, firstly I copy the image and then, when I paste it in the vscode, the message show that 'No image in clipboard'.

### Logs

>No image in clipboard

### Desktop

Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by tecosaur** [comment]
Hmmm. That's not very good.
On windows the script used (no avalible vscode api unfortunately) is [here](https://github.com/tecosaur/LaTeX-Utilities/blob/master/scripts/saveclipimg-pc.ps1). I don't have windows so I can't debug it, do you think you may be able to try it out and report back?

**Comment by hktkzyx** [comment]
I solved it. The reason is that I directly copy the image file in Windows Explorer, so the image is not copied in the clipboard. If I open the image in an image viewer and copy it, the image is in the clipboard and it works well.

**Comment by tecosaur** [comment]
Is the path to the image copied to the clipboard? Because that _should_ also work

**Comment by hktkzyx** [comment]
I haven't copied the image path. Copying the image file does work.
