### ISSUE TITLE
How would one use sympy in snippets?

### ISSUE THREAD

**Issue by ThunderSmotch** [tecosaur/LaTeX-Utilities#43]
Assuming that the user has python3 and sympy package installed using the snippets provided by default shouldn't the text `sympy 1+1 sympy` return the replacemente 2 ?

In my case when I run sympy the text gets replaced by "SYMPY_CALCULATING" and then by an empty string, returning nothing.

**Comment by tecosaur** [comment]
Huh. Works for me. What do you see in the output panel?

**Comment by ThunderSmotch** [comment]
Nothing shows up in the output panel no matter which log I select to view.

**Comment by tecosaur** [comment]
How would you feel about debuging?

**Comment by tecosaur** [comment]
The issue is probably somewhere in

https://github.com/tecosaur/LaTeX-Utilities/blob/f4387441768cd4d6dcb6ec969738f3181a5f4ba0/src/components/completionWatcher.ts#L340-L387

**Comment by ThunderSmotch** [comment]
I'll try to take a look and if I find anything I'll let you know!

**Comment by tecosaur** [comment]
Any luck?

**Comment by tecosaur** [comment]
@ThunderSmotch \*cough

**Comment by ThunderSmotch** [comment]
Hey sorry but so far I haven't been able to figure out where the problem lies, gonna try to compile the python code and run it from cmd to see if that works. I'll post something when I have progress.

**Comment by tecosaur** [comment]
@ThunderSmotch I can't reproduce this myself, which means I need your help to solve it :)

**Comment by leoleoasd** [comment]
Closing for no action for a long time
