### ISSUE TITLE
Default Values in tabstops not working

### ISSUE THREAD

**Issue by ThunderSmotch** [tecosaur/LaTeX-Utilities#44]
### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: Yes

### Describe the bug

Can't use default values in tabstops in live snippets

### To Reproduce

Steps to reproduce the behaviour:

Use this snippet:
    {
        "prefix": "\\bdint$",
        "body": "\\int_{$${1:-\\infty}}^{$${2:\\infty}} ",
        "mode": "maths",
        "triggerWhenComplete": true
    }

Will yield:
`\int_{${1:-\infty}}^{${2:\infty}} `

### Expected behaviour

Should've yielded `\int_{-\infty}^{\infty} `  with two tabstops at each argument of the integral.

### Desktop

-   OS: Windows 10
-   VS Code version: 1.38.1
-   Extension version: 0.3.0

Off-topic: Sorry for bothering you so much today. ☹️

**Comment by tecosaur** [comment]
Hmm. I'll debug that to see what's going on. I'll have a go later today.

Off-topic: I'd rather have all the things that don't work pointed out so the can be fixed. It's not good if the default snippets don't work.
