### ISSUE TITLE
How to configure latex-utilities.countWord.args? 

### ISSUE THREAD

**Issue by Ramzh** [tecosaur/LaTeX-Utilities#47]
Hi there, I am a beginner with LatTeX via VSCode, I was able to set up all everything I needed to start a document and build/display it correctly, however I am unable to see the wordCount currently.

I have the following settings: 
```
{
    "workbench.iconTheme": "vscode-icons",
    "latex-workshop.view.pdf.viewer": "tab",
    "workbench.startupEditor": "newUntitledFile",
    "latex-utilities.countWord.path": "/.config/TeXcount/texcount.pl",
    "latex-utilities.countWord.args": ["-merge %DOC%"]
}
```
 And currently set WordCount shortcut as ctrl+alt+w but still nothing happens, I tried Googling around but was not able to find a solution. Any help on this would be appreciated!

Thanks

**Comment by tecosaur** [comment]
Does pulling up the command from the command palette work?

**Comment by tecosaur** [comment]
@Ramzh if you could check that out I'd be appriciated.

**Comment by codingToPerfection** [comment]
I still dont know if `"latex-utilities.countWord.args": ["-merge %DOC%"]` works... can someone tell me?
