### ISSUE TITLE
List of triggers for livesnippets

### ISSUE THREAD

**Issue by maikol-solis** [tecosaur/LaTeX-Utilities#48]
### Is your feature request related to a problem? Please describe.

It would be nice to have a list of triggers for the live snippet feature. I suppose that the idea is to mimic a little the workflow of https://castel.dev/post/lecture-notes-1/ but in vscode. For example, the superscript trigger is not clear for me at least. 

### Describe the solution you'd like

Just a list in the documentation or inside the extension where the user could learn how to trigger all the livesnippets.

### Describe alternatives you've considered

Try to decipher the latexUtilsLiveSnippets.json file to learn the triggers. 

### Additional context

none

**Comment by tecosaur** [comment]
Did the [wiki page](https://github.com/tecosaur/LaTeX-Utilities/wiki/Live-Snippets) help at all?

**Comment by maikol-solis** [comment]
The wiki gives how the livesnippet is constructed, but not how to trigger particularly each one. It would be nice if for example there was a list with two columns saying 

|Text| Autocompletion |
|-|-|
|a1|a_1|

etc..

**Comment by tecosaur** [comment]
Ah. I see, that should be easy to add :)

**Comment by tecosaur** [comment]
What do you think of it now?

**Comment by maikol-solis** [comment]
Perfect!
