### ISSUE TITLE
Add table cell delimiter as a variable setting

### ISSUE THREAD

**Issue by chrisjsewell** [tecosaur/LaTeX-Utilities#56]
## Feature Request

As the title says, it would be helpful to be able to use different delimiters for table cells, rather than having it hard coded as `"\t"`, e.g. `","` for pasting CSVs and  `" " `  for pasting from excel.

At a minimum this would be a global setting, e.g. `latex-utilities.formattedPaste.tableHeaderDelimiter` or, for a more fancy solution, a question box could pop up during the conversion, asking the user which delimiter to use (pre-populated with the default).

(apart from this, it's a very helpful extension thanks :))

**Comment by tecosaur** [comment]
@chrisjsewell thanks for not just reporting the issue but also making PRs that solves it! It's great to see this.

I can't quite tell where I'd use this personally, so to better compare the adequateness of the current and proposed solutions would you mind explaining the issue a bit more?

At the moment as far as I know excel uses tab delimination (`\t`), and you can paste `csv` files by location (but not extracts of one).

I'd quite like this sorts of feature to "just work" for the user, so if there are a few different common formats perhaps the best approach would be to try to intellegently identify the common ones and process them appropriately, then provide a setting which enables the 'prompt box' you suggested.

I look forward to hearing from you :)

**Comment by chrisjsewell** [comment]
> @chrisjsewell thanks for not just reporting the issue but also making PRs that solves it! It's great to see this.

No problem :)

Well certainly on my Mac excel pastes with spaces, and also in VS Code by default (I believe) tabs are automatically converted to spaces, so just in general there are no cases when `\t` works for me.

In #58 I could add a setting to turn on/off the prompt, but it does already initialise with the correct delimiter (based on the `latex-utilities.formattedPaste.tableColumnDelimiter` and whether it was a CSV file location), so it does "just work", but after typing `Shift+Cmnd+V` you additionally have to hit `Enter` to confirm the delimiter

**Comment by chrisjsewell** [comment]
Hmm, that's annoying, it does actually appear to be tabs for Excel but, if I try to use `Shift+Cmnd+V` directly it fails (which I'm sure was working earlier with spaces!), but if I paste it to VS Code and then copy it from there, it works:

![latex_formatpaste_excel](https://user-images.githubusercontent.com/2997570/66894700-01e95c80-efe9-11e9-87cd-e0e73dbce33c.gif)

But anyway, here is an example of how #58 works

![latex_formatpaste](https://user-images.githubusercontent.com/2997570/66893593-54754980-efe6-11e9-846c-b43efba78a1a.gif)

**Comment by tecosaur** [comment]
Huh. That is annoying. It works directly for me, would you be willing to debug why direct pasting isn't working?

By the way, did you have any thoughts on this?
> ... intelligently identify the common [formats] and process them appropriately.

**Comment by chrisjsewell** [comment]
> debug why direct pasting isn't working

It is because of https://github.com/tecosaur/LaTeX-Utilities/blob/39503509fdaf338ccf8554c07ce7e5bbf583d230/src/components/paster.ts#L113

If I use `s.replace(/[^\S\t]+$/gm, '').replace(/^[\uFEFF\xA0]+|[\uFEFF\xA0]+$/gm, '')` it works, so presumably mac excel has a different new line format. I thought maybe `\r\n`, but I can't get an alternative regex to work.

>  intelligently identify the common [formats] 

Nothing simple comes to mind, but now in #58 I have made the prompt optional (turned off by default), so there is now no change to the default functionality.

**Comment by tecosaur** [comment]
Based on what you said it looks like there's some important whitespace (not tabs) at the start being stripped. No idea what that could be.

I'll take a look at #58 tommorow :)

**Comment by chrisjsewell** [comment]
> Based on what you said it looks like there's some important whitespace (not tabs) at the start being stripped. No idea what that could be.

Fixed it :) (see the last commit in #58)

I confirmed that the delimiter is `\r\n` (which is the old standard for mac newlines). What was  happening, is that it saw the `\r` as the newline delimiter, then thought the `\n` was at the start of the next line, and stripped it. Adding `s.replace('\r\n', '\n')` stops this occurring.
