### ISSUE TITLE
Change name and description of `latex-utilities.tikzpreview.parseTeXFile`

### ISSUE THREAD

**Issue by chrisjsewell** [tecosaur/LaTeX-Utilities#59]
> Enable important tikz code in the current TeX file to be included in tikzpreview standalone file

This is not really a good description of what this variable actually does in the code. It controls whether the content read from the preamble file (not the current TeX file) is filtered for only tikz specific commands.

See: https://github.com/tecosaur/LaTeX-Utilities/blob/0f31b5b42ce32892176054fa9777618e78f2c315/src/components/tikzpreview.ts#L294

I suggest changing the name to `latex-utilities.tikzpreview.filterPreamble` (then reversing the conditional in the code), and the description to something like:

> Filter the preamble file for tikz related commands only, before adding to the tikzpreview standalone file.

**Comment by tecosaur** [comment]
Hmmm. I'm not sure your interpretation is correct.
Looking at `tikzpreview.ts` if `parseTeXFile` is set then the filtering is run on the following file:
```js
fs.readFileSync(fileTikzCollection.location, { encoding: 'utf8' })
```
This file is provided as the argument to the `generatePreamble`. It is an instance of `IFileTikzCollection`.

Looking a bit further this looks like a case of bad variable naming on my part (sorry) as `location` actually refers to the location of the working TeX file. I've renamed it in 39503509fdaf338ccf8554c07ce7e5bbf583d230. Hopefully, this will resolve any confusion.

I appriciate you going through my code to look for such issues though :smiley:
