### ISSUE TITLE
Wordcount is not working

### ISSUE THREAD

**Issue by werunom** [tecosaur/LaTeX-Utilities#6]
### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: Yes

### Describe the bug

The version-8 changelog of `latex-workshop` extension mentions that word counting functionality has been moved to this extension. 

But when I search for a command in latex-utilities, there is nothing related to word-count. For instance, the command-pallette does not show anything. 
![S - 2](https://user-images.githubusercontent.com/24664855/63261983-6ebecf80-c2a2-11e9-9f0a-313979ead3a2.png)

The command present in the latex-explorer, also does not do anything when clicked
![S - 3](https://user-images.githubusercontent.com/24664855/63262046-9ada5080-c2a2-11e9-9b18-d7c92c0f2356.png)

Also there seems to be redundant word-count commands. When searched for word count command, I get the following command
![S - 1](https://user-images.githubusercontent.com/24664855/63262079-ad548a00-c2a2-11e9-8573-1bd7373f8fcf.png)

Executing this, gives `command 'latex-workshop.wordcount' not found`
### Desktop

-   OS: Linux manjaro
-   VS Code version: 1.37.1
-   Extension version: 0.1.0
- Latex-Workshop version: 8.0.3

**Comment by tecosaur** [comment]
If you take a look at the [changelog](https://github.com/tecosaur/LaTeX-Utilities/blob/master/CHANGELOG.md) you'll see that the word count feature was added in v0.2, which has just been published :slightly_smiling_face:

For the issues with `command 'latex-workshop.wordcount' not found` you'll want to report that on the LaTeX Workshop side of things.

**Comment by werunom** [comment]
I just received the update for v0.2. Thanks!

I will report the remaining issues in the parent extension
