### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by QWERDFBEST** [tecosaur/LaTeX-Utilities#68]
### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: Yes

### Describe the bug

Can not run commands
![image](https://user-images.githubusercontent.com/55515181/67709036-d704ee00-f982-11e9-8fc6-18c3e58c5148.png)

### Logs

Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output</summary>

```
logs here
```

</details>

<details>
<summary>LaTeX Utilities Output</summary>

```
logs here

```

</details>

<details>
<summary>Developer Tools Console</summary>

```
logs here
```

</details>

### Screenshots

![image](https://user-images.githubusercontent.com/55515181/67709321-509cdc00-f983-11e9-8ec5-3d773f425ac3.png)
![image](https://user-images.githubusercontent.com/55515181/67710003-bccc0f80-f984-11e9-9484-ac84da8c96d0.png)

### Desktop

-   OS: [e.g. Windows 10]
-   VS Code version: [e.g. 1.39.2]
-   Extension version: [e.g. 0.3.3]

**Comment by tecosaur** [comment]
That's … interesting. I can't say I've seen that before. Is there anything more you can find out?

**Comment by tecosaur** [comment]
@QWERDFBEST  \*cough

**Comment by QWERDFBEST** [comment]
I didn't find out other things, or where can I find more details things?

**Comment by assignUser** [comment]
@QWERDFBEST Which VSC Version are you using? And which version of Latex-Utilities?
Try updating both.

**Comment by tecosaur** [comment]
Closing until such a time that @QWERDFBEST is able to add more.
