### ISSUE TITLE
Pasting tables larger than 2xN doesn't auto-format

### ISSUE THREAD

**Issue by LeCyberDucky** [tecosaur/LaTeX-Utilities#79]
#### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: **Yes**

### Describe the bug

Copying and pasting matrices/tables form Excel into a .tex file doesn't automatically get formatted for matrix dimensions greater than 2 x N. It seems to work well for an arbitrary number of columns, but it doesn't work for more than two rows. 

Instead of a nicely formatted table, the rows just get pasted as a single line of numbers. 

### To Reproduce

Steps to reproduce the behaviour:

Open fresh Excel document. Type in random numbers in a 3 x 2 matrix. Copy the numbers and paste them into a .tex file in VS Code using ctrl + shift + V. See that the result is not as expected. 

### Expected behaviour

Pasting using ctrl + shift + V should result in a LaTeX-formatted table for matri

### Logs

Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output</summary>

```
Logs unrelated, I think. 
```

</details>

<details>
<summary>LaTeX Utilities Output</summary>

```
[19:52:41] Performing formatted paste
[19:52:41] Pasting: Table
[19:52:41] No table found
```

</details>

<details>
<summary>Developer Tools Console</summary>

```
Not sure about suspicious things here. 
```

</details>

### Desktop

-   OS: Windows 10 
-   VS Code version: 1.40.0
-   Extension version: 0.3.4

**Comment by tecosaur** [comment]
Hello :)

It seems that I don't have this issue
![image](https://user-images.githubusercontent.com/20903656/68630309-de4efe80-0521-11ea-8153-9280aa35a1d8.png)
(libre office) produces this when pasted:
```tex
\begin{tabular}{lll}
	\toprule
	a & b & c \\
	\midrule
	1 & 2 & 3 \\
	x & y & z \\
	\bottomrule
\end{tabular}
```

This extension uses the plaintext version of the table in the clipboard and parses `\t` and `\n` for cell/row separation.
To help me track this down would you mind pasting the 3×n selection of cells into here/Pastebin (I just need the `\t` tab characters to be retained) so I can try out what excel is giving you?

Thanks!

**Comment by LeCyberDucky** [comment]
Hey :)

Here is a working example of a 2x3 matrix copied from Excel: https://pastebin.com/c0WS0HEd

And here I added another row to make it 3x3. This doesn't work: https://pastebin.com/tYuJNhXL

Does that help? I'm not sure if this gives you the information you need. I'll paste them below directly in the comment, just in case: 

`

1 | 2 | 3
-- | -- | --
4 | 5 | 6

`

`

1 | 2 | 3
-- | -- | --
4 | 5 | 6
7 | 8 | 9

`

Thanks for taking a look at the issue :)

**Comment by tecosaur** [comment]
No problem, I'd like it to do what it says it will after all :smiley:.

Thanks for providing the pastes.
On a less positive note, I'm afraid I haven't been able to reproduce what you're seeing, I took the 'raw pastebin' for the 3×3 and put it into hexdump. I got this:
```
00000000  31 09 32 09 33 0a 34 09  35 09 36 0a 37 09 38 09  |1.2.3.4.5.6.7.8.|
00000010  39 0a                                             |9.|
00000012
```
Reproducing the 3×3 in libre calc and pasting gave me this:
```
00000000  31 09 32 09 33 0a 34 09  35 09 36 0a 37 09 38 09  |1.2.3.4.5.6.7.8.|
00000010  39 0a                                             |9.|
00000012
```
It's worth noting that `09`=tab and `0a`=newline.

This may be because I'm running HEAD instead of v0.3.4 though, I'll give this a test a bit later.

Hopefully we'll be able to work out what the difference is so we can fix it.

**Comment by LeCyberDucky** [comment]
I installed hexdump in a try to investigate this too. 

So, I input the numbers in a new Excel file. Then I copied them and pasted them into an empty .txt file. Running hexdump on that file gives me the following: 

`00000000: 31 09 32 09 33 0D 0A 34  09 35 09 36 0D 0A 37 09  1.2.3..4.5.6..7.
00000010: 38 09 39 0D 0A                                    8.9..`

**Comment by tecosaur** [comment]
Thanks for doing this, it makes my job a lot easier :)

I spot the same difference.  Where I have `0A` (`\n`) you have `0D 0A` (`\r\n`). So this would have me guess it's a CRLF vs LF thing. _However,_ I have `.replace('\r\n', '\n')` in the table parsing for _exactly_ that reason.

Since I'm still having issues reproducing this; if you're willing to do a bit more, could you try running HEAD instead of v0.3.4? It would be nice to just confirm this is still an issue here. (git clone + `npm i` + degug/run (`F5`) in vscode)

I'd also be interested in seeing the output of line 123 as `trimUnwantedWhitespace` is what should resolve the CRLF/LF thing. (add debug point, paste again and see what happens)
https://github.com/tecosaur/LaTeX-Utilities/blob/e157485de93f886f7bed3a79a91e02d9ae6bdaae/src/components/paster.ts#L123

_p.s. re: hexdump formatting, I think that's just a difference in what we used. I used the command line linux tool_

**Comment by LeCyberDucky** [comment]
Okay, I think I did what you wanted me to do =) 

I installed Node.js and then I cloned the repository onto my computer and did `npm i` inside that folder. Then I opened the folder in VS Code and hit F5 to run it (after adding the wanted break point). That opened another VS Code window, where I went to my .tex file and tried pasting a 3x3 table. 

As I'm not entirely sure how to give you the wanted output, I'll show you two screenshots of what `content` looks like before and after line 123: 

![image](https://user-images.githubusercontent.com/19520383/68693462-9fe42e80-0577-11ea-9ecb-7da99e566f48.png)

![image](https://user-images.githubusercontent.com/19520383/68693504-affc0e00-0577-11ea-877d-a78f0acd75ba.png)

I hope this gives you the wanted information. Tell me if there is more I can do to help =)

**Comment by tecosaur** [comment]
I really appreciate how willing you are to help me track down the issue :smiley: 

Thanks, your screenshots do indeed help! It looks like `trimUnwantedWhitespace` is messing it up. Now we just need to work out which line of regex. 

Would you mind going through the `s.replace(...).replace(...)` lines in `trimUnwantedWhitespace` and seeing if you can spot where things go wrong?

https://github.com/tecosaur/LaTeX-Utilities/blob/e157485de93f886f7bed3a79a91e02d9ae6bdaae/src/components/paster.ts#L118-L122

I'm still not sure why you are experencing this issue and I'm not, but hopefully this test will help us find out.

**Comment by LeCyberDucky** [comment]
Here are some screenshots of what things look like for each steep of `trimUnwantedWhitespace` (don't mind the extra line I added. That was just a try to get breakpoint things to work more in my favor. Didn't really help, though.):

![image](https://user-images.githubusercontent.com/19520383/68742068-8aaae680-05ef-11ea-9cd5-9fbb11e70042.png)

![image](https://user-images.githubusercontent.com/19520383/68742090-94cce500-05ef-11ea-9833-a437bc1f1375.png)

![image](https://user-images.githubusercontent.com/19520383/68742113-a0b8a700-05ef-11ea-94ce-b3812c52caef.png)

![image](https://user-images.githubusercontent.com/19520383/68742128-aa420f00-05ef-11ea-9a52-0bc94c228d2b.png)

![image](https://user-images.githubusercontent.com/19520383/68742151-b4fca400-05ef-11ea-82b7-d4c0bc60fb9b.png)

![image](https://user-images.githubusercontent.com/19520383/68742165-bf1ea280-05ef-11ea-96fc-e7f5ea56ec0d.png)


Okay, this has got me stumped now. I'm not sure what's going on here. Does it look like it somehow magically breaks from the last `.replace()` and onwards? 

I tried taking the initial value of `content` and replicating this in python, but there it doesn't seem to break? 

![image](https://user-images.githubusercontent.com/19520383/68742498-9cd95480-05f0-11ea-8beb-7a29615f9461.png)

**Comment by tecosaur** [comment]
Hmm. I think you may need to rewrite `trimUnwantedWhitespace` to the following for useful debugging, ATM it's just showing the same things three times over.

```ts
const trimUnwantedWhitespace = (s: string) => {
    s = s.replace('\r\n', '\n')
    s = s.replace(/^[^\S\t]+|[^\S\t]+$/gm, '')
    s = s.replace(/^[\uFEFF\xA0]+|[\uFEFF\xA0]+$/gm, '')
    return s
}
```

**Comment by LeCyberDucky** [comment]
Ah, yes. Changing the function to that gives me the following. So I think it breaks on the second `.replace()`? 

![image](https://user-images.githubusercontent.com/19520383/68793059-d2139000-064c-11ea-8280-6f185172a8dc.png)

![image](https://user-images.githubusercontent.com/19520383/68793087-de97e880-064c-11ea-8326-a2508468f2d2.png)

![image](https://user-images.githubusercontent.com/19520383/68793111-ebb4d780-064c-11ea-8d06-9821b76dce99.png)

![image](https://user-images.githubusercontent.com/19520383/68793143-f7a09980-064c-11ea-91af-65d618998659.png)

**Comment by tecosaur** [comment]
I think I may have identified the issue, and boy do I feel silly. Please let me know if this function works for you (`'\r\n'` to `/\r\n/g`):
```ts
const trimUnwantedWhitespace = (s: string) => {
    s = s.replace(/\r\n/g, '\n')
    s = s.replace(/^[^\S\t]+|[^\S\t]+$/gm, '')
    s = s.replace(/^[\uFEFF\xA0]+|[\uFEFF\xA0]+$/gm, '')
    return s
}
```

**Comment by LeCyberDucky** [comment]
Yup, that seems to do the trick! 

Would you mind briefly explaining the problem? This whole thing is interesting to me, and I don't understand why the old version worked when I tried replicating it in python. The new version looks more "regex-y" to me, whereas the old version looked more like normal "find-and-replace string". Is it something along those lines? 

Anyway, thanks a lot for taking the time to work on this with me =)

**Comment by tecosaur** [comment]
The issue is a momentary lapse in concentration when writing that. Javascript's `.replace('string', ...` will only replace the _first_ instance which it comes across, you need `.replace(/string/g, ...` to replace _every_ instance. This is why the 2x2 table worked.

Anyway, glad that this fixes things and thanks for all your help tracking this down :smiley:
