### ISSUE TITLE
Add a Wiki

### ISSUE THREAD

**Issue by trevorgunn** [tecosaur/LaTeX-Utilities#8]
The feature set is small right now, so I'm thinking either one large page or one page per feature.

**Comment by tecosaur** [comment]
Given that this is likely to continue to grow, that may not be a bad idea. Even if they're short pages I think I'll go for one page per feature.

**Comment by tecosaur** [comment]
The only thing that needs documenting ATM is live snippets — which has now been done: https://github.com/tecosaur/LaTeX-Utilities/wiki/Live-Snippets.
