### ISSUE TITLE
texcount output parsing error

### ISSUE THREAD

**Issue by assignUser** [tecosaur/LaTeX-Utilities#80]
### Describe the bug

When texcount encounters a \documentclass with arguments that are split over multiple lines like this:
```
\documentclass[
12pt,
oneside,
parskip=half,
headsepline=true,
]{scrartcl}
``` 
it will fail to find the correct class unless it is called with the `-relaxed` argument (as explained [here](https://tex.stackexchange.com/a/160832/155446)). This results in a change in the texcount outputs first line to this:
```
!!! Could not identify document class. !!!
File: test.tex
Encoding: utf8
Words in text: 5689
Words in headers: 57
[...]
```
Which leads to an empty log output ` TeXCount output: `  due to a failure to parse during the call to `parseTexcount`:

<details>
<summary>Developer Tools Console</summary>
```
Error: String was not valid TexCount output
	at WordCounter.parseTexCount (c:\Users\User\.vscode-insiders\extensions\tecosaur.latex-utilities-0.3.4\out\src\components\wordCounter.js:119:19)
```
</details>

### Desktop

-   OS: Windows 10 
-   VS Code version: 1.40.0-insider
-   Extension version: 0.3.4

**Comment by tecosaur** [comment]
Sorry for the delayed reply. Thanks for identifying the `-relaxed` flag, testing the HEAD version though a file like your sample produces the `!!! Could not identify document class. !!!` error but the output is still parsed
```
[01:11:02] TeXCount output: 78+1+0 (1/0/0/0) File: tikzcl.tex
[01:11:09] TeXCount output: 79+1+0 (1/0/0/0) File: tikzcl.tex
```
Would you be able to provide a full MWE for me to test so I can try to reproduce this issue?

**Comment by assignUser** [comment]
```
\documentclass[
12pt
]{scrartcl}

\begin{document}
this is a test!
\end{document}
```
This does not produce output for me (without the relaxed flag) with extension version 0.3.4 I am not familiar enough with ts and vsc extensions to package the HEAD version my self for testing, sorry.

**Comment by tecosaur** [comment]
Thanks! I'll give that a shot and see what I can do.

**Comment by assignUser** [comment]
Oh maybe also interesting: I am using the texcount version from Miktex which is version 3.1.1 
That may also be diffrent in out setups. Thanks for you quick answers and all the Work you put into the Latex-* vsc extensions! Thanks to you I can use vsc for EVERYTHING 😄

**Comment by tecosaur** [comment]
I'm also on `3.1` so that should work. Sorry I haven't been particularly responsive on the issue.
Running `texcount -brief` on that MWE you gave (as the extension does) gave me this.
```
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/\\\w+({ <-- HERE })?/ at /usr/bin/texcount line 2934.

!!! Could not identify document class. !!!
4+0+0 (0/0/0/0) File: ./temp.tex
(errors:1)
```
The extension filters out all `(error:*)` lines and then takes the last one for processing. Hence I am not supprised to see
```
[18:31:38] TeXCount output: 4+0+0 (0/0/0/0) File: temp.tex
```
and then in the activity bar: (I'm using `$(book) ${headers} Headings ${words} Words`)
![image](https://user-images.githubusercontent.com/20903656/69139243-11cdf200-0afb-11ea-8ea6-8d939b926628.png)

Would you mind running `texcount -brief` on your file so I can compare your output to mine?

#### p.s.
Thanks for the kind words, as a hobby project hearing appreciation does wonders for motivation :smiley:

**Comment by assignUser** [comment]
ok I did some "debugging" with some console.logging and found out the following:
args: `["-brief","-merge"]`
Output texcount (note the empty newline): 
```
!!! Could not identify document class. !!!
4+0+0 (0/0/0/0) File: test.tex
(errors:1)
 
```
<del>For some reason I don't understand</del> the empty new line does not get `.filter`ed, because it seems to contain spaces (why mine has spaces and yours does not? No clue):
```
 ["
", "!!! Could not identify document class. !!!
", "4+0+0 (0/0/0/0) File: test.tex
", "
"]
```
Which of course causes .parseTexCount to freak out. Atleast the solution is easy.

Here is my modified code:
```js
// just get the last line, ignoring errors
stdout = stdout
    .replace(/\(errors:\d+\)/, '')
    .split('\n')
    .map(l => l.trim())
    .filter(l => l !== '')
    .slice(-1)[0];
this.extension.logger.addLogMessage(`TeXCount output: ${stdout}`);
resolve(this.parseTexCount(stdout));
```

**Comment by tecosaur** [comment]
Wow! You've done all the work for me :stuck_out_tongue: thanks! I've got not idea why you get extra blank lines, but I'm glad that you found a solution :smiley:

I'll put this out in the next update (I'd guess that it's going to be v0.4.0 out in a week or two).
