### ISSUE TITLE
Local \tikzset are recognized as global

### ISSUE THREAD

**Issue by joulev** [tecosaur/LaTeX-Utilities#9]
Consider the following MWE

```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
  \draw (0,0) -- (3,0);
  \fill (0,0) circle (1.5pt) node[left] {$A$};
  \fill (3,0) circle (1.5pt) node[right] {$B$};
\end{tikzpicture}

\begin{tikzpicture}
  \tikzset{every node/.style={fill=white,draw}}
  \draw (0,0) -- (0,-2) node[below,minimum size=1cm] {$m$};
\end{tikzpicture}
\end{document}
```

The second Ti*k*Z picture has a `\tikzset`, but it is only a local one, i.e. all other Ti*k*Z pictures are *not* affected by this `\tikzset`. To show it, this is the output of the above code

![image](https://user-images.githubusercontent.com/44609036/63402476-c295f980-c405-11e9-97e6-38f009ba858a.png)

However, LaTeX Utilities recognizes the `\tikzset` as a global one, so the style in the second Ti*k*Z picture is also applied to the first. This is the preview of the first Ti*k*Z picture, which is obviously not right.

![image](https://user-images.githubusercontent.com/44609036/63402550-0852c200-c406-11e9-8442-6eb488c5e3e3.png)

I think **there should be a boolean checker to check whether a `\tikzset` should be included in `tikzpicture-XXX.tex`**. This particular case is only a simple case. In some other cases, some options in different local `\tikzset`s conflict with each other, that may lead to the break of the complete Ti*k*Z preview system. Or a `minimum size` in a local `\tikzset` can cause weird preview for the other pictures.

---

Regarding in what case `\tikzset` should be included, in my personal experience,

1. If `\tikzset` is before `\begin{document}`, always include it.
2. Otherwise, `\tikzset` is only applied to Ti*k*Z elements **in the same group** AND **after the `\tikzset` command** AND **before another `\tikzset` command of *the same* group**.

(1) is obvious. (2) is almost obvious, but you should test the following case:

<details>
<summary>Code</summary>

```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
  \node {1};
\end{tikzpicture}

\begingroup
  \begin{tikzpicture}
    \node {2};
  \end{tikzpicture}
  
  \tikzset{every node/.style={text=red}}

  \begin{tikzpicture}
    \node {3};
  \end{tikzpicture}

  \tikzset{every node/.style={text=blue}}

  \begin{tikzpicture}
    \node {4};
  \end{tikzpicture}
\endgroup

\begin{tikzpicture}
  \node {5};
\end{tikzpicture}
\end{document}
```

`\begingroup` can be replaced by `\begin{any-environment}` and so can `\endgroup`. Note that `any-environment` can be `tikzpicture` itself!
</details>
<details>
<summary>Output</summary>

![image](https://user-images.githubusercontent.com/44609036/63403859-3b4b8480-c40b-11e9-96cb-f96f22f4478c.png)

</details>
<details>
<summary>Current (21 Aug) preview</summary>

![image](https://user-images.githubusercontent.com/44609036/63403924-72ba3100-c40b-11e9-99f9-768e7d4883e1.png)
![image](https://user-images.githubusercontent.com/44609036/63403948-89608800-c40b-11e9-8481-5fd53f5f2e1e.png)
![image](https://user-images.githubusercontent.com/44609036/63403960-98473a80-c40b-11e9-8927-c224dae815e7.png)
![image](https://user-images.githubusercontent.com/44609036/63403978-a8f7b080-c40b-11e9-9dd2-5201e09aef4c.png)
![image](https://user-images.githubusercontent.com/44609036/63404011-b90f9000-c40b-11e9-9292-e52a6f61985c.png)
</details>

---

* **Operating system:** Windows 10
* **VS Code version:** 1.37.1
* **LaTeX Workshop version:** 8.0.4
* **LaTeX Utilities version:** 0.2.1

**Comment by tecosaur** [comment]
Sorry this is taking a while. (1) should be fixed in 6df7e3cd0bfb39c381f57958f6451f1a39ab65f4. I'll get to (2) later.

**Comment by tecosaur** [comment]
@joulev do you think the current state of this is alright?

**Comment by tecosaur** [comment]
There we go! Took me long enough.
